import Head from 'next/head'
import Comments from '../containers/Comments'
import Layout from '../containers/Layout'
import Main from '../containers/Main'
import News from '../containers/News'
import Partners from '../containers/Partners'
import PostSection from '../containers/PostSection'

export default function Home({data,news}) {
  // console.log(data);
  return (
    <>
      <Head>
        <title>Домашняя страница</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <Layout>
          <h1>{}</h1>
          <Main/>
          <PostSection dataProf={data}/>
          <Comments/>
          <News dataProps={news}/>
          <Partners/>
        </Layout>
      </div>
    </>
      
  )
}

export async function getServerSideProps(context){
  const res = await fetch('http://localhost:1337/professions')
  const data = await res.json()
  const result = await fetch('http://localhost:1337/news-columns')
  const news = await result.json()
  return{
    props:{data,news},
  }
}