import Head from 'next/head'
import Layout from '../containers/Layout'
import Main from '../containers/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Домашняя страница</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <Layout>
          <Main/>
        </Layout>
      </div>
    </>
      
  )
}
